version: '2'

services:
  devenv:
    container_name: intellij-devcontainer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    command: sleep infinity
    user: devenv
